version: '3.7'

services:
  db:
    container_name: advent_db
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./config/.db.prod.env

  web:
    container_name: advent_web
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: myapp:latest
    env_file:
      - ./config/.env.prod
    command: >
      bash -c "python manage.py migrate
      && python manage.py collectstatic --no-input
      && python manage.py makemessages -a
      && python manage.py compilemessages
      && gunicorn advent_naughty.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
      - /var/certbot/conf:/etc/letsencrypt/:ro
    expose:
      - 8000
    depends_on:
      - db

  bot:
    container_name: advent_bot
    image: myapp:latest
    env_file:
      - ./config/.env.prod
    command: python manage.py run_bot
    depends_on:
      - db

  task:
    container_name: advent_task
    image: myapp:latest
    env_file:
      - ./config/.env.prod
    command: python manage.py run_task
    depends_on:
      - db

  nginx:
    build: ./nginx
    restart: unless-stopped
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
    ports:
      - 1337:1337
      - 8443:8443
    depends_on:
      - web

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    depends_on:
      - nginx

volumes:
  postgres_data:
  static_volume:
  media_volume: