# Generated by Django 5.0 on 2023-12-28 16:15

import django.db.models.deletion
import djrichtextfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Порядковый номер ячейки')),
                ('description', models.CharField(max_length=250, verbose_name='Содержимое')),
                ('message_image', models.ImageField(upload_to='upload/', verbose_name='Баннер сообщении')),
                ('webapp_image', models.ImageField(upload_to='upload/', verbose_name='Фото миниапп')),
                ('content', djrichtextfield.models.RichTextField(max_length=1010, verbose_name='Текст под фото')),
                ('additional_info', djrichtextfield.models.RichTextField(blank=True, max_length=4000, null=True, verbose_name='Текст доп сообщении')),
                ('open_date', models.DateField(verbose_name='Когда будет доступен')),
            ],
            options={
                'verbose_name': 'Ячейка',
                'verbose_name_plural': 'Ячейки',
            },
        ),
        migrations.CreateModel(
            name='PlannedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', djrichtextfield.models.RichTextField(max_length=1010, verbose_name='Текст под баннер')),
                ('additional_info', djrichtextfield.models.RichTextField(blank=True, max_length=4000, null=True, verbose_name='дополнительный текст')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('send_time', models.DateTimeField(verbose_name='Время отправки')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщении',
            },
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='Ид в телеграмм')),
                ('first_name', models.CharField(max_length=128, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Фамилия')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='tg username')),
            ],
            options={
                'verbose_name': 'Телеграм пользователь',
                'verbose_name_plural': 'Телеграм пользователи',
            },
        ),
        migrations.CreateModel(
            name='MessageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload/')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.plannedmessage')),
            ],
            options={
                'verbose_name': 'карточка сообщении',
                'verbose_name_plural': 'карточки сообщении',
            },
        ),
        migrations.CreateModel(
            name='TgMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(default=None, editable=False, null=True, verbose_name='Дата создания')),
                ('planned_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plannedmessage', verbose_name='Сообщение')),
                ('tg_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tguser', verbose_name='Тг пользователь')),
            ],
            options={
                'verbose_name': 'Отпр сообщения',
                'verbose_name_plural': 'Отпр сообщении',
            },
        ),
        migrations.CreateModel(
            name='UserCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_opened', models.BooleanField(default=False)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cell', verbose_name='Ячейке')),
                ('tg_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tguser', verbose_name='Пользователь')),
            ],
        ),
    ]
