# Generated by Django 5.0 on 2023-12-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='name',
            field=models.CharField(default='', max_length=126, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='webapp_image',
            field=models.ImageField(upload_to='upload/', verbose_name='Аватар'),
        ),
    ]
