# Generated by Django 5.0 on 2023-12-29 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cell_name_alter_cell_webapp_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell',
            name='message_image',
        ),
        migrations.AlterField(
            model_name='cell',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Краткое описание'),
        ),
        migrations.CreateModel(
            name='CellMessageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload/')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.cell')),
            ],
            options={
                'verbose_name': 'карточка сообщении',
                'verbose_name_plural': 'карточки сообщении',
            },
        ),
    ]
